### ISSUE TITLE
Unknown server error

### ISSUE THREAD

**Issue by bitchery** [tropicbliss/buckshot#3] opened 2021-07-08 19:14 UTC
Yeah.. I have no idea. Just typed in my name snipe and it just says unknown server error, can't get this to work sadly.

![image](https://user-images.githubusercontent.com/87142512/124977917-03fb1680-e029-11eb-8b84-6b228b8423bb.png)

**Comment by tropicbliss** [comment] 2021-07-09 02:53
Sorry for the inconvenience. Can you please try this again? It might be a server issue on my end.

**Comment by bitchery** [comment] 2021-07-09 06:47
Seems like it's working alright now, thank you.

Quick question - I'm new to all of this, how do I GC snipe using this sniper?

Thanks in advance :)

**Comment by tropicbliss** [comment] 2021-07-09 08:35
Set gc_snipe in config.toml to true. When faced with the prompt of whether you have redeemed your giftcode or not, just press the ENTER key if you have, or enter the giftcode if you have not. Note that people had trouble with this sniping when GC sniping, and I'm really not sure why it doesn't work for them, but feel free to try it.

**Comment by bitchery** [comment] 2021-07-09 11:16
Awesome, thanks for the help. I'll try it out later. :)

**Comment by bitchery** [comment] 2021-07-09 11:18
surely I'd have to redeem the giftcode, because when I try to snipe without it redeemed I get this?

![image](https://user-images.githubusercontent.com/87142512/125070366-c392ab80-e0af-11eb-9500-e768fd39c398.png)

**Comment by tropicbliss** [comment] 2021-07-09 12:08
Oh dang. I think I know the issue. I'll get back to you when the issue is solved.

**Comment by tropicbliss** [comment] 2021-07-09 12:46
Alright issue should be fixed. Try again and see if it works.

**Comment by bitchery** [comment] 2021-07-09 13:07
So I can use buckshot to snipe in this field?

![image](https://user-images.githubusercontent.com/87142512/125082204-d8c30680-e0be-11eb-8870-bd0c30874f94.png)

I've just claimed the giftcode and I was wondering whether it would snipe using this. I think it works, since it tells me it's sniping the name in the correct elapsed time. Would it help having multiple instances of buckshot running to increase my chances? or does it not work like that?

Seems like you fixed it though, all good now.

**Comment by bitchery** [comment] 2021-07-09 13:41
Also, is it possible to load multiple accounts for more requests to the API via buckshot? thanks

**Comment by tropicbliss** [comment] 2021-07-09 14:26
You cannot run multiple instances of buckshot in a single machine because the Mojang API has IP rate limiting. It also has account rate limiting which means that you'll have to snipe on a different account on a different IP address.

**Comment by bitchery** [comment] 2021-07-09 14:36
I see, thanks for the help! You've been a great help :)

Appreciate it man, thanks for the program

**Comment by bitchery** [comment] 2021-07-09 14:38
what does the spread do?

**Comment by tropicbliss** [comment] 2021-07-09 15:03
Just leave the spread alone, you don't really need it. The more the spread the more spread out the requests will be.

**Closed** 2021-07-09 15:03 UTC
